// Typelizer digest df3467e5b767ec9487665b3115122a45
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedRootUserData = AlbaUser
type AlbaInheritedRootUser = {
  root_user: AlbaInheritedRootUserData;
}

export default AlbaInheritedRootUser;
