// Typelizer digest 925e7d8390988ffee8bc4c22b10a9709
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaPost} from "@/types"

type AlbaPreferDoubleQuotes = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sir_name: string;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latest_post: AlbaPost | null;
  custom_key_posts: Array<AlbaPost>;
  first_name: string;
}

export default AlbaPreferDoubleQuotes;
