// Typelizer digest 298d06421463aace62810542724911b2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserRole} from '@/types'

type AlbaNestedAttribute = {
  username: string;
  name: string;
  details: {
    role: UserRole;
    timestamps: {
      created_at: string;
      updated_at: string;
    };
  };
}

type AlbaNestedAttributeWithUserRoleTrait = {
  user_role: {
    role: UserRole;
  };
}

export default AlbaNestedAttribute;
export type { AlbaNestedAttributeWithUserRoleTrait };
