// Typelizer digest 92876f27e9e78123c69c34e8db673ad6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaPost, UserRole} from "@/types"

type AlbaPreferDoubleQuotes = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sir_name: string;
  role: UserRole;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latest_post: AlbaPost | null;
  /** Aliased posts collection */
  custom_key_posts?: Array<AlbaPost>;
  first_name: string;
}

export default AlbaPreferDoubleQuotes;
