// Typelizer digest b3db08c937d12de78cbc0a05ad554c40
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: AlbaComment;
  replies: Array<AlbaComment>;
}

export default AlbaComment;
