// Typelizer digest 57c228a0bddbb2c2d4e510ed77e7a890
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default AlbaSorted;
