// Typelizer digest a15038f14b182bb1c9c132d05b11bfab
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaTraits, AlbaPost, AlbaTraitsBasicTrait, AlbaTraitsComplexTrait, AlbaPostDetailsTrait, AlbaPostWithAuthorTrait, AlbaTraitsCustomAttributesTrait} from '@/types'

type AlbaTraitsAssociations = {
  user: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  latest_post: AlbaPost & AlbaPostDetailsTrait | null;
}

type AlbaTraitsAssociationsAssociationsTrait = {
  user: AlbaTraits & AlbaTraitsCustomAttributesTrait;
}

type AlbaTraitsAssociationsWithPostsTrait = {
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

type AlbaTraitsAssociationsFullTrait = {
  invitor: AlbaTraits & AlbaTraitsBasicTrait | null;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  username: string;
}

type AlbaTraitsAssociationsWithAliasedAssociationsTrait = {
  user_alias: AlbaTraits;
  custom_posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

export default AlbaTraitsAssociations;
export type { AlbaTraitsAssociationsAssociationsTrait, AlbaTraitsAssociationsWithPostsTrait, AlbaTraitsAssociationsFullTrait, AlbaTraitsAssociationsWithAliasedAssociationsTrait };
