// Typelizer digest 3bc70e01a03431f2290729fcd38dcd0b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaArUser} from '@/types'

type AlbaArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: AlbaArUser | null;
}

export default AlbaArPost;
