// Typelizer digest 912a7b0b2fe99e9d6451c56612a2f28c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaPoro = {
  foo: unknown;
  bar: string | null;
}

export default AlbaPoro;
