// Typelizer digest 099471cc43b1b4b38cb951219a444ef8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaTypeMappingOverride = {
  attr_decimal: string;
  attr_float: number;
  attr_integer: number;
  attr_date: string;
}

export default AlbaTypeMappingOverride;
