// Typelizer digest 07496c17e996b72df90947b4d18b4940
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedCustomTypeUser = Omit<AlbaUser, 'id'> & {
  /** Unique identifier */
  id?: number | null;
}

export default AlbaInheritedCustomTypeUser;
