// Typelizer digest 4ae310a1251d74e6f28b68d806dd3a5a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedRootUserData = AlbaUser
type AlbaInheritedRootUser = {
  root_user: AlbaInheritedRootUserData;
}

export default AlbaInheritedRootUser;
