// Typelizer digest 1444a0edea7f80963356001ae58b6eb5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, PostCategory} from '@/types'

type AlbaPost = {
  id: number;
  title?: string | null;
  category?: PostCategory | null;
  body?: string | null;
  published_at?: string | null;
  user: AlbaUser;
  created_by: AlbaUser;
  next_post: Post;
  previous_post: AlbaPost;
  /** This is name
   * @deprecated */
  name: string;
}

type AlbaPostDetailsTrait = {
  excerpt: string;
  word_count: number;
}

type AlbaPostWithAuthorTrait = {
  user: AlbaUser;
  created_by: AlbaUser;
}

export default AlbaPost;
export type { AlbaPostDetailsTrait, AlbaPostWithAuthorTrait };
