// Typelizer digest 8c0e713748fd03eb3f5c738d02dd9e78
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { AlbaVerbatimModuleSyntax };
