// Typelizer digest 1f9c0aa4990a456612d866b504d0a8ff
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaInline = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  post_ids: Array<number>;
  untyped_posts: Array<{
    id: unknown;
    title: unknown;
  }>;
  posts: Array<{
    id: number;
    title: string;
  }>;
  deep_posts: Array<{
    id: number;
    title: string | null;
    user: {
      id: number;
      username: string;
    };
  }>;
}

export default AlbaInline;
