// Typelizer digest 7f156ed6b3fe76a0f93937655abaa114
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaArUser} from '@/types'

type AlbaArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: AlbaArUser | null;
}

export default AlbaArPost;
