// Typelizer digest 4e6d41fd64683f1a68258ace48c7adad
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedExtendedUser = AlbaUser & {
  full_name: string;
}

export default AlbaInheritedExtendedUser;
