// Typelizer digest b77660ba6ebcbef3bdb1729e24fd6b42
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaPostDetailsTrait, AlbaPostWithAuthorTrait, AlbaTraits, AlbaTraitsBasicTrait, AlbaTraitsComplexTrait} from '@/types'

type AlbaSortedImports = {
  user: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  latest_post: AlbaPost & AlbaPostDetailsTrait | null;
}

export default AlbaSortedImports;
