// Typelizer digest f4f5d614bbc86ecf0fac1caee9964a08
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaCustomOutputDir} from '@/types'

type AlbaAttributesApi = {
  /** Unique identifier */
  id: string;
  attr_string: string;
  attr_integer: number;
  attr_float: number;
  attr_decimal: number;
  attr_boolean: boolean;
  attr_datetime: string;
  attr_date: string;
  attr_time: string;
  attr_json: unknown;
  attr_array: Array<string>;
  attr_range: Array<number>;
  custom_output: AlbaCustomOutputDir;
}

export default AlbaAttributesApi;
