// Typelizer digest 3020caba9dce866826c1462bd279c931
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaArPost} from '@/types'

type AlbaArUser = {
  /** Unique identifier */
  id: string;
  username: string;
  skills: Array<unknown>;
  settings: Record<string, unknown>;
  metadata: unknown;
  invitor: AlbaArUser;
  posts: Array<AlbaArPost>;
  latest_post: AlbaArPost;
}

export default AlbaArUser;
