// Typelizer digest ebbde5d66b7d507d6a44d6713ea34d16
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaInheritedExtendedUser} from '@/types'

type AlbaInheritedDeepUser = AlbaInheritedExtendedUser & {
  updated_at: string;
}

export default AlbaInheritedDeepUser;
