// Typelizer digest 3426579309776d13e307b45ff5780c4c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser, AlbaPostDetailsTrait} from '@/types'

type AlbaTraits = {
  /** Unique identifier */
  id: string;
  invitor: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait | null;
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
  latest_post: AlbaPost & AlbaPostDetailsTrait | null;
}

type AlbaTraitsBasicTrait = {
  attr_string: string;
  attr_integer: number;
  attr_float: number;
  attr_boolean: boolean;
}

type AlbaTraitsTimeRelatedTrait = {
  attr_datetime: string;
  attr_date: string;
  attr_time: string;
}

type AlbaTraitsComplexTrait = {
  attr_json: unknown;
  attr_array: Array<string>;
  attr_range: Array<number>;
}

type AlbaTraitsCustomAttributesTrait = {
  url: string;
}

type AlbaTraitsWithOptionsTrait = {
  optional_field: string | null;
  nullable_name: string | null;
}

type AlbaTraitsMixedTrait = {
  username: string;
  name: string;
  user: AlbaUser;
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

type AlbaTraitsEmptyTrait = {
}

export default AlbaTraits;
export type { AlbaTraitsBasicTrait, AlbaTraitsTimeRelatedTrait, AlbaTraitsComplexTrait, AlbaTraitsCustomAttributesTrait, AlbaTraitsWithOptionsTrait, AlbaTraitsMixedTrait, AlbaTraitsEmptyTrait };
