// Typelizer digest 5ee874bf4e3a3a2b3e9f283060188bec
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaMetaNil = {
  /** Unique identifier */
  id: string;
}

export default AlbaMetaNil;
