// Typelizer digest bdd7629a3f8e4b1b303dba168e371216
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: AlbaComment;
  replies: Array<AlbaComment>;
}

export default AlbaComment;
