// Typelizer digest 3866c6219b26cbf0559af9d90106c265
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaPost} from '@/types'

type AlbaTransformKeys = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sirName: string;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latestPost: AlbaPost | null;
  customKeyPosts: Array<AlbaPost>;
  firstName: string;
  createdAt: string;
}

export default AlbaTransformKeys;
