// Typelizer digest f8e75a4b9244dcdf1ea5cd6d19a22b4f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default AlbaSorted;
