// Typelizer digest e206f8f3463ae840255217d6e2fe39d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, PostCategory, UserRole} from '@/types'

type AlbaInline = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  post_ids: Array<number>;
  untyped_posts: Array<{
    id: unknown;
    title: unknown;
  }>;
  posts: Array<{
    id: number;
    title: string;
  }>;
  deep_posts: Array<{
    id: number;
    title: string | null;
    category: PostCategory | null;
    author: AlbaUser;
    user: {
      id: number;
      username: string;
      role: UserRole;
    };
  }>;
}

export default AlbaInline;
