// Typelizer digest 26804ed8a65817f3a8523d22f81e3716
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser} from '@/types'

type AlbaInheritedTransformKeysUser = Omit<AlbaUser, 'sir_name' | 'latest_post' | 'custom_key_posts' | 'first_name'> & {
  /** This is sir name from the name */
  sirName: string;
  latestPost: AlbaPost | null;
  customKeyPosts: Array<AlbaPost>;
  firstName: string;
}

export default AlbaInheritedTransformKeysUser;
