// Typelizer digest 75cb2f7edaae070630830d54a512f791
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AdminRole} from '@/types'

type AlbaAdmin = {
  custom_attr: string;
  label: string;
  /** Unique identifier */
  id: string;
  username: string;
  name: string;
  role: AdminRole;
  active: boolean;
}

export default AlbaAdmin;
