// Typelizer digest bc1c68490d505901513ffdd18578efd0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaInheritedRootUser} from '@/types'

type AlbaInheritedNestedRootUserData = AlbaInheritedRootUser['root_user'] & {
  updated_at: string;
}

type AlbaInheritedNestedRootUser = {
  nested_root_user: AlbaInheritedNestedRootUserData;
}

export default AlbaInheritedNestedRootUser;
