// Typelizer digest 2b0ea30fb53a5e22d5f764f87d1e2a8f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaTraits, AlbaPost, AlbaTraitsBasicTrait, AlbaTraitsComplexTrait, AlbaPostDetailsTrait, AlbaPostWithAuthorTrait, AlbaTraitsCustomAttributesTrait} from '@/types'

type AlbaTraitsAssociations = {
  user: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  latest_post: AlbaPost & AlbaPostDetailsTrait | null;
}

type AlbaTraitsAssociationsAssociationsTrait = {
  user: AlbaTraits & AlbaTraitsCustomAttributesTrait;
}

type AlbaTraitsAssociationsWithPostsTrait = {
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

type AlbaTraitsAssociationsFullTrait = {
  invitor: AlbaTraits & AlbaTraitsBasicTrait | null;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  username: string;
}

type AlbaTraitsAssociationsWithAliasedAssociationsTrait = {
  user_alias: AlbaTraits;
  custom_posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

export default AlbaTraitsAssociations;
export type { AlbaTraitsAssociationsAssociationsTrait, AlbaTraitsAssociationsWithPostsTrait, AlbaTraitsAssociationsFullTrait, AlbaTraitsAssociationsWithAliasedAssociationsTrait };
