// Typelizer digest 6710172932d9902cb3aefd3394d38e76
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {TypeZ, TypeA, TypeM, ZebraSection, AlphaSection, BetaSection, UserRole} from '@/types'

type AlbaUnionSorted = {
  email: string;
  /** Unique identifier */
  id: string;
  items: Array<TypeA | TypeM | TypeZ>;
  role: UserRole;
  sections: AlphaSection | BetaSection | ZebraSection;
  status: 'apple' | 'banana' | 'zebra';
  username: string;
}

export default AlbaUnionSorted;
