// Typelizer digest 920ff62833de1bcca9e3ad1a0d2be083
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaPost, UserRole} from '@/types'

type AlbaTransformKeys = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sirName: string;
  role: UserRole;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latestPost: AlbaPost | null;
  customKeyPosts: Array<AlbaPost>;
  firstName: string;
  createdAt: string;
}

type AlbaTransformKeysWithProfileTrait = {
  latestPost: AlbaPost | null;
}

type AlbaTransformKeysWithDetailsTrait = {
  myCustomPosts: Array<AlbaPost>;
}

export default AlbaTransformKeys;
export type { AlbaTransformKeysWithProfileTrait, AlbaTransformKeysWithDetailsTrait };
