// Typelizer digest bc0d85697989a69319bb294de28175f9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedExtendedUser = AlbaUser & {
  full_name: string;
}

export default AlbaInheritedExtendedUser;
