// Typelizer digest f7db5bbd6c9f607bf7a8ab9f403cd6e4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaPostDetailsTrait, AlbaPostWithAuthorTrait, AlbaTraits, AlbaTraitsBasicTrait, AlbaTraitsComplexTrait} from '@/types'

type AlbaSortedImports = {
  user: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait;
  posts: Array<AlbaPost & AlbaPostDetailsTrait & AlbaPostWithAuthorTrait>;
  latest_post: AlbaPost & AlbaPostDetailsTrait | null;
}

export default AlbaSortedImports;
