// Typelizer digest 295062293a0ef5e6554a5fdbb9a58e10
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaMetaData = {
  username: string;
  full_name: string | null;
  address: {city: string, zipcode: string};
}

type AlbaMeta = {
  meta: AlbaMetaData;
  metadata: {foo: 'bar'};
}

export default AlbaMeta;
