// Typelizer digest 25aabcec5272fb8ea354e8acb68983d2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaAbstractBase = {
  custom_attr: unknown;
  label: string;
}

export default AlbaAbstractBase;
