// Typelizer digest 24666b2c8ef094193c02028c06115055
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost} from '@/types'

type AlbaUser = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sir_name: string;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latest_post: AlbaPost | null;
  custom_key_posts: Array<AlbaPost>;
  first_name: string;
}

export default AlbaUser;
