// Typelizer digest 856a2762a106c17132aa659b4e062964
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser} from '@/types'

type AlbaUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<AlbaPost>;
  invitor: AlbaUser;
  avatar: unknown;
  /** Typed avatar URL
   * Active user only */
  typed_avatar: string | null;
}

export default AlbaUserEmptyNested;
