// Typelizer digest 995c76aa8fe279e753d23a6d7c4eb723
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { AlbaVerbatimModuleSyntax };
