// Typelizer digest eacb46f235da7e2921cdd6c920d4eeb1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsArPost} from '@/types'

type AmsArUser = {
  /** Unique identifier */
  id: string;
  username: string;
  skills: Array<unknown>;
  settings: Record<string, unknown>;
  metadata: unknown;
  invitor: AmsArUser;
  posts: Array<AmsArPost>;
  latest_post: AmsArPost;
}

export default AmsArUser;
