// Typelizer digest 9cbf8be0d61deb97b7e014543be00103
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsArUser} from '@/types'

type AmsArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: AmsArUser | null;
}

export default AmsArPost;
