// Typelizer digest 82b09099a7973cfcf61d5d9650d9b982
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsArDelegate = {
  /** Unique identifier */
  id: string;
  name: string | null;
  user_username: string;
  author_active: boolean;
  user_role: number | null;
}

export default AmsArDelegate;
