// Typelizer digest e17e9e5e27464ded626bedca9280369b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsArUser} from '@/types'

type AmsArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: AmsArUser | null;
}

export default AmsArPost;
