// Typelizer digest 40ce099a00d1ee4850f08fd010acc3b4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: AmsComment;
  replies: Array<AmsComment>;
}

export default AmsComment;
