// Typelizer digest 4fbbc386947dc7e3c7169e4c303b4785
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: AmsComment;
  replies: Array<AmsComment>;
}

export default AmsComment;
