// Typelizer digest d4852f81c26a9b496cdf355f7a6a586d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsComment} from '@/types'

type AmsClassRef = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  reviewer?: AmsUser | null;
  editor: AmsUser;
  approver: AmsUser | null;
  commentable: AmsUser | AmsComment;
  mixed_ref: AmsUser | AmsComment;
  contributors: Array<AmsUser> | null;
}

export default AmsClassRef;
