// Typelizer digest 370648c006690acaf4e5edc921063a1b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsInheritedCustomTypeUser = Omit<AmsUser, 'id'> & {
  /** Unique identifier */
  id?: number | null;
}

export default AmsInheritedCustomTypeUser;
