// Typelizer digest 9cc1667984d1ebfe330e93e17a97334c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsInheritedCustomTypeUser = Omit<AmsUser, 'id'> & {
  /** Unique identifier */
  id?: number | null;
}

export default AmsInheritedCustomTypeUser;
