// Typelizer digest dc8cf5addac2c3f404d7d77d5ef99409
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsInheritedTransformKeysUser = AmsUser & {
  createdAt: string;
}

export default AmsInheritedTransformKeysUser;
