// Typelizer digest c6e2e2f13a41b82ee306819ad91b9c62
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsInheritedExtendedUser} from '@/types'

type AmsInheritedDeepUser = AmsInheritedExtendedUser & {
  updated_at: string;
}

export default AmsInheritedDeepUser;
