// Typelizer digest 08d7b2c77b3242a3beaa50d64207bd7d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsPost} from "@/types"

type AmsPreferDoubleQuotes = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsPreferDoubleQuotes;
