// Typelizer digest 11a06e443697f348488b39cf5b0a1630
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, PostCategory} from '@/types'

type AmsPost = {
  id: number;
  title?: string | null;
  category?: PostCategory | null;
  body?: string | null;
  published_at?: string | null;
  previous_post: AmsPost;
  /** @deprecated Use 'title' instead. */
  name: string;
  user: AmsUser;
  created_by: AmsUser;
}

export default AmsPost;
