// Typelizer digest c991aca1812484ed7354bd45dcf87e1d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default AmsSorted;
