// Typelizer digest a36bbfd40b96d00529cd6cafcf56d333
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default AmsSorted;
