// Typelizer digest 303acc0aaf41dabe5c2c22c4859b43b7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsPost} from '@/types'

type AmsTransformKeys = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  createdAt: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsTransformKeys;
