// Typelizer digest 9e708374efd2a7c84f769b1f9da858f1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default AmsTypeShortcuts;
