// Typelizer digest 53c3aebe239b343f0b0743a9632d1e09
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsPost} from '@/types'

type AmsTransformKeys = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  createdAt: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsTransformKeys;
