// Typelizer digest fd33bc6a70a8ed8dd2ccf0563e53e4d8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsPost} from '@/types'

type AmsUser = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsUser;
