// Typelizer digest 4f711d79f31e9635ef16174621ce7ac0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsPost} from '@/types'

type AmsUserSerializerFoo = {
  /** Unique identifier */
  id?: number | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  created_at: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsUserSerializerFoo;
