// Typelizer digest 76917cd789c2c5deb2d09b685f633e1e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsPost} from '@/types'

type AmsUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts?: Array<AmsPost>;
}

export default AmsUserAuthor;
