// Typelizer digest 7135c395958101112cb5fe8808117388
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsPost} from '@/types'

type AmsUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts?: Array<AmsPost>;
}

export default AmsUserEmptyNested;
