// Typelizer digest 682efca5d7511526d31d2e368d55a357
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { AmsVerbatimModuleSyntax };
