// Typelizer digest 42601a39caafcfbfc24ebecb8ec213ed
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { AmsVerbatimModuleSyntax };
