// Typelizer digest 66840ae9d13f8fa39ff59b50c56a62f8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type AdminRole = 'guest' | 'member' | 'admin' | 'superadmin';
export type PostCategory = 'news' | 'article' | 'blog';
export type UserRole = 'guest' | 'member' | 'admin' | 'superadmin';
