// Typelizer digest 5345b961b3a0e06b98e8f9d956cc676e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default OjSerializersTypeShortcuts;
