// Typelizer digest 0e0e127674bb9d0759a9cf31c45e9546
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<OjSerializersPost>;
  avatar: unknown;
  typed_avatar: string | null;
}

export default OjSerializersUserAuthor;
