// Typelizer digest 28d18d257dc41f17d0acd3d6b9c2d86f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersInheritedEmptyUser = OjSerializersUser
export default OjSerializersInheritedEmptyUser;
