// Typelizer digest 18a9ad09c1f8a476fa7eb445ab0e5dd5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUser = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersUser;
