// Typelizer digest 8277d185c43e59637676422ee9cb5469
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<OjSerializersPost>;
  avatar: unknown;
  typed_avatar: string | null;
}

export default OjSerializersUserEmptyNested;
