// Typelizer digest 843792f5793c70e0768b039a28cf8727
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: OjSerializersComment;
  replies: Array<OjSerializersComment>;
}

export default OjSerializersComment;
