// Typelizer digest 778702a5b905940a6944a178c23b0a29
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { OjSerializersVerbatimModuleSyntax };
