// Typelizer digest e221ccf74c0c13438d2673d8b79a9180
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersInheritedCustomTypeUser = Omit<OjSerializersUser, 'id'> & {
  /** Unique identifier */
  id?: number;
}

export default OjSerializersInheritedCustomTypeUser;
