// Typelizer digest 7d3f2d35961316db2181d0af932f39da
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default OjSerializersTypeShortcuts;
