// Typelizer digest 32c416ec97e9c98986b48a9d014fce24
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from '@/types'

type OjSerializersTransformKeys = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  firstName: string;
  createdAt: string;
}

export default OjSerializersTransformKeys;
