// Typelizer digest b8aa9126b86b12c8d917bd27f9b45aa0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersArPost} from '@/types'

type OjSerializersArUser = {
  /** Unique identifier */
  id: string;
  username: string;
  skills: Array<unknown>;
  settings: Record<string, unknown>;
  metadata: unknown;
  invitor: OjSerializersArUser;
  posts: Array<OjSerializersArPost>;
  latest_post: OjSerializersArPost;
}

export default OjSerializersArUser;
