// Typelizer digest 5186e50df3927874364a3ee708428a06
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from "@/types"

type OjSerializersPreferDoubleQuotes = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersPreferDoubleQuotes;
