// Typelizer digest ce40c1dea6851d3b722d58c5455c419b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersComment = {
  /** Unique identifier */
  id: string;
  body: string;
  parent?: OjSerializersComment;
  replies: Array<OjSerializersComment>;
}

export default OjSerializersComment;
