// Typelizer digest e2c6e91a9c155a2f249e542cfee11348
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from '@/types'

type OjSerializersUserSerializerFoo = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
  created_at: string;
}

export default OjSerializersUserSerializerFoo;
