// Typelizer digest 60d8893714eecfa1fe78adce168ebcab
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersComment} from '@/types'

type OjSerializersClassRef = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  reviewer?: OjSerializersUser | null;
  editor: OjSerializersUser;
  approver: OjSerializersUser | null;
  commentable: OjSerializersUser | OjSerializersComment;
  mixed_ref: OjSerializersUser | OjSerializersComment;
  contributors: Array<OjSerializersUser> | null;
}

export default OjSerializersClassRef;
