// Typelizer digest 2bd66e161ece1b7322abcece7dfd6340
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUser = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersUser;
