// Typelizer digest 4bbf69b7d777d04b9a434e5661800763
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersArPost} from '@/types'

type OjSerializersArUser = {
  /** Unique identifier */
  id: string;
  username: string;
  skills: Array<unknown>;
  settings: Record<string, unknown>;
  metadata: unknown;
  invitor: OjSerializersArUser;
  posts: Array<OjSerializersArPost>;
  latest_post: OjSerializersArPost;
}

export default OjSerializersArUser;
