// Typelizer digest 0a321ed10af7a1e7cc7fe84d95e1030b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from '@/types'

type OjSerializersFlatUser = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersFlatUser;
