// Typelizer digest 672abb444029862dca53baac2d10e77d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<OjSerializersPost>;
  avatar: unknown;
  typed_avatar: string | null;
}

export default OjSerializersUserEmptyNested;
