// Typelizer digest bd60ca01536bc00c0531fdc724a8b486
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from "@/types"

type OjSerializersPreferDoubleQuotes = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersPreferDoubleQuotes;
