// Typelizer digest 8ca60c4cafff50bb27bdd26d8533152b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from '@/types'

type OjSerializersFlatUser = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  first_name: string;
}

export default OjSerializersFlatUser;
