// Typelizer digest 0d08083a5c62428fe7b948eedb7837f1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersInheritedTransformKeysUser = Omit<OjSerializersUser, 'first_name'> & {
  firstName: string;
}

export default OjSerializersInheritedTransformKeysUser;
