// Typelizer digest d263b621499bd3c11087ff72062a6e6d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default OjSerializersSorted;
