// Typelizer digest 66fd3cc3440253aaa9a2fd3baf4966c1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost} from '@/types'

type PankoUser = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  posts: Array<PankoPost>;
  invitor: PankoUser | null;
  latest_post: PankoPost | null;
}

export default PankoUser;
