// Typelizer digest e13f102738ee992702c75a0b34cb66db
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser, PankoComment} from '@/types'

type PankoClassRef = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  reviewer?: PankoUser | null;
  editor: PankoUser;
  approver: PankoUser | null;
  commentable: PankoUser | PankoComment;
  mixed_ref: PankoUser | PankoComment;
  contributors: Array<PankoUser> | null;
}

export default PankoClassRef;
