// Typelizer digest 07549ab1146d5623d797153dc4a3092e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost, PankoUser} from "@/types"

type PankoPreferDoubleQuotes = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  posts: Array<PankoPost>;
  invitor: PankoUser | null;
  latest_post: PankoPost | null;
}

export default PankoPreferDoubleQuotes;
