// Typelizer digest abf7dbcfe4a14086e540eb48d1c051bb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoArUser} from '@/types'

type PankoArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: PankoArUser | null;
}

export default PankoArPost;
