// Typelizer digest a2a29045940f667315f8531c089157fb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoComment = {
  /** Unique identifier */
  id: string;
  body: string;
  replies: Array<PankoComment>;
  parent?: PankoComment;
}

export default PankoComment;
