// Typelizer digest 0ef7a6c27376c679a8c6b51e465aee58
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoInheritedExtendedUser} from '@/types'

type PankoInheritedDeepUser = PankoInheritedExtendedUser & {
  updated_at: string;
}

export default PankoInheritedDeepUser;
