// Typelizer digest f357e4af1c54091750fa58bc84ceeebd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default PankoTypeShortcuts;
