// Typelizer digest 7166fe4ea15813fe09f19172a8a3e4fb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoArUser} from '@/types'

type PankoArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: PankoArUser | null;
}

export default PankoArPost;
