// Typelizer digest 41dc5cd8118599eeab92de587410a43d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost} from '@/types'

type PankoUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts: Array<PankoPost>;
}

export default PankoUserAuthor;
