// Typelizer digest 8ef4ad51cb55aa33150d53106626ad9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser, PostCategory} from '@/types'

type PankoPost = {
  id: number;
  title?: string | null;
  category?: PostCategory | null;
  body?: string | null;
  published_at?: string | null;
  previous_post: PankoPost;
  user: PankoUser;
  created_by: PankoUser;
}

export default PankoPost;
