// Typelizer digest 7bd1d21ee59ba493a94f7f7519360fc5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default PankoSorted;
