// Typelizer digest 30b02f7eaa6120fd1531c47f2cfc8c28
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default PankoSorted;
