// Typelizer digest 39540a80bf3db66f7cc64a19e79ee21a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser} from '@/types'

type PankoInheritedCustomTypeUser = Omit<PankoUser, 'id'> & {
  /** Unique identifier */
  id?: number | null;
}

export default PankoInheritedCustomTypeUser;
