// Typelizer digest 5e52010169a4123e0423da348751e819
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser} from '@/types'

type PankoInheritedEmptyUser = PankoUser
export default PankoInheritedEmptyUser;
