// Typelizer digest 73a450734c46377617da4c34aa023205
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoArPost} from '@/types'

type PankoArUser = {
  /** Unique identifier */
  id: string;
  username: string;
  skills: Array<unknown>;
  settings: Record<string, unknown>;
  metadata: unknown;
  posts: Array<PankoArPost>;
  invitor: PankoArUser;
  latest_post: PankoArPost;
}

export default PankoArUser;
