// Typelizer digest 1408be52dcb4a359dc20d17f8f167376
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default PankoTypeShortcuts;
