// Typelizer digest 3c0d37869384e60571eb45b4abf8df57
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost} from '@/types'

type PankoUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts: Array<PankoPost>;
}

export default PankoUserEmptyNested;
