// Typelizer digest 560d088b08f837b0854bc35b3747daac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost, PankoUser} from '@/types'

type PankoUserSerializerFoo = {
  /** Unique identifier */
  id?: number | null;
  username: string;
  active: boolean;
  name: string;
  created_at: string;
  first_name: string;
  posts: Array<PankoPost>;
  invitor: PankoUser | null;
  latest_post: PankoPost | null;
}

export default PankoUserSerializerFoo;
