// Typelizer digest 78a73c5d6e4a010816dcff39a814039f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as adminUsers } from './Admin/UsersController'
export { default as blogEngineArticles } from './BlogEngine/ArticlesController'
export { default as pages } from './PagesController'
export { default as posts } from './PostsController'
export { default as users } from './UsersController'

import _pages from './PagesController'
import _posts from './PostsController'
import _users from './UsersController'
import _adminUsers from './Admin/UsersController'
import _blogEngineArticles from './BlogEngine/ArticlesController'

export const root = _pages.index
export const userPosts = _posts.userPosts
export const userPost = _posts.userPost
export const newUser = _users.new
export const editUser = _users.edit
export const user = _users.show
export const newPost = _posts.new
export const editPost = _posts.edit
export const post = _posts.post
export const adminUser = _adminUsers.show
export const page = _pages.show
export const archive = _posts.archive
export const articles = _blogEngineArticles.index
export const article = _blogEngineArticles.show
