source "https://rubygems.org"

ruby ">= 3.0"
gem "rails", "~> 7.1.3"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

gem "oj_serializers"
gem "alba"
gem "active_model_serializers"

gem "typelizer", path: "../.."

gem "rspec-rails"
