// Typelizer digest 92f824d3fb5ac2cad8ea1bbd95fe0067
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /blog/articles */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/blog/articles', {}, options),
    method: 'get',
  }),

  /** GET /blog/articles/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/blog/articles/:id', params, options),
    method: 'get',
  }),
}
