// Typelizer digest 8df6444ab0a39c33d9fc031442975218
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, FormDefinition, RouteOptions } from '../runtime'
import { buildUrl, formAction } from '../runtime'

export default {
  /** GET /admin/users */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/users', {}, options),
    method: 'get',
  }),

  /** GET /admin/users/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/users/:id', params, options),
    method: 'get',
  }),

  /** DELETE /admin/users/:id */
  destroy: Object.assign(
    (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): RouteDefinition<'delete'> => ({
      url: buildUrl('/admin/users/:id', params, options),
      method: 'delete',
    }),
    { form: (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): FormDefinition =>
      formAction(buildUrl('/admin/users/:id', params, options), 'delete') },
  ),
}
