// Typelizer digest a74bd4c3713a775de91c51a6d2a4c368
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type PostCategory = 'news' | 'article' | 'blog';
export const PostCategory = { news: 'news', article: 'article', blog: 'blog' } as const;
export type UserRole = 'guest' | 'member' | 'admin' | 'superadmin';
export const UserRole = { guest: 'guest', member: 'member', admin: 'admin', superadmin: 'superadmin' } as const;
