// Typelizer digest c95828dab2b4f5d17f40afba93888a8a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaMetaData = {
  username: string;
  fullName: string | null;
  address: {city: string, zipcode: string};
}

type AlbaMeta = {
  meta: AlbaMetaData;
  metadata: {foo: 'bar'};
}

export default AlbaMeta;
