// Typelizer digest 9638b9e02eb6288c6c0a2e136312c8dc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserRole} from '@/types'

type AlbaNestedAttribute = {
  username: string;
  name: string;
  details: {
    role: UserRole;
    timestamps: {
      createdAt: string;
      updatedAt: string;
    };
  };
}

type AlbaNestedAttributeWithUserRoleTrait = {
  userRole: {
    role: UserRole;
  };
}

export default AlbaNestedAttribute;
export type { AlbaNestedAttributeWithUserRoleTrait };
