// Typelizer digest e0bc724dc014ffc14dbbb91ee9a558cf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedExtendedUser = AlbaUser & {
  fullName: string;
}

export default AlbaInheritedExtendedUser;
