// Typelizer digest 15a96f85f1309b983145de4cb7e0b1b2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, PostCategory} from '@/types'

type AlbaPost = {
  id: number;
  title?: string | null;
  category?: PostCategory | null;
  body?: string | null;
  publishedAt?: string | null;
  user: AlbaUser;
  createdBy: AlbaUser;
  nextPost: Post;
  previousPost: AlbaPost;
  /** This is name
   * @deprecated */
  name: string;
}

type AlbaPostDetailsTrait = {
  excerpt: string;
  wordCount: number;
}

type AlbaPostWithAuthorTrait = {
  user: AlbaUser;
  createdBy: AlbaUser;
}

export default AlbaPost;
export type { AlbaPostDetailsTrait, AlbaPostWithAuthorTrait };
