// Typelizer digest 639fa963defe1d6efe00fa681a27478f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser, AlbaPostDetailsTrait} from '@/types'

type AlbaTraits = {
  /** Unique identifier */
  id: string;
  invitor: AlbaTraits & AlbaTraitsBasicTrait & AlbaTraitsComplexTrait | null;
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
  latestPost: AlbaPost & AlbaPostDetailsTrait | null;
}

type AlbaTraitsBasicTrait = {
  attrString: string;
  attrInteger: number;
  attrFloat: number;
  attrBoolean: boolean;
}

type AlbaTraitsTimeRelatedTrait = {
  attrDatetime: string;
  attrDate: string;
  attrTime: string;
}

type AlbaTraitsComplexTrait = {
  attrJson: unknown;
  attrArray: Array<string>;
  attrRange: Array<number>;
}

type AlbaTraitsCustomAttributesTrait = {
  url: string;
}

type AlbaTraitsWithOptionsTrait = {
  optionalField: string | null;
  nullableName: string | null;
}

type AlbaTraitsMixedTrait = {
  username: string;
  name: string;
  user: AlbaUser;
  posts: Array<AlbaPost & AlbaPostDetailsTrait>;
}

type AlbaTraitsEmptyTrait = {
}

export default AlbaTraits;
export type { AlbaTraitsBasicTrait, AlbaTraitsTimeRelatedTrait, AlbaTraitsComplexTrait, AlbaTraitsCustomAttributesTrait, AlbaTraitsWithOptionsTrait, AlbaTraitsMixedTrait, AlbaTraitsEmptyTrait };
