// Typelizer digest 4df8b03eee2fae873dc2b4016cea3a14
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type PostCategory = 'news' | 'article' | 'blog';
export type UserRole = 'guest' | 'member' | 'admin' | 'superadmin';
