// Typelizer digest bffe42731b1b640f0cdcc4c0f38ce9e6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost} from '@/types'

type AlbaCustomOutputDir = {
  /** Unique identifier */
  id: string;
  username: string;
  posts: Array<AlbaPost>;
}

export default AlbaCustomOutputDir;
