// Typelizer digest a14d50f38be1c0056b38d2d6ded9ebf1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/users */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/users', {}, options),
    method: 'get',
  }),

  /** GET /admin/users/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/users/:id', params, options),
    method: 'get',
  }),

  /** DELETE /admin/users/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/admin/users/:id', params, options),
    method: 'delete',
  }),
}
