// Typelizer digest 08dfd09fd9d2826556cc13899cf2c835
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaArDelegate = {
  /** Unique identifier */
  id: string;
  name: string | null;
  user_username: string;
  author_active: boolean;
  user_role: number | null;
}

export default AlbaArDelegate;
