// Typelizer digest 8e8452f21dd1a8736beba59e1bbfcd1b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser} from '@/types'

type AlbaUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<AlbaPost>;
  invitor: AlbaUser;
  avatar: unknown;
  /** Typed avatar URL
   * Active user only */
  typed_avatar: string | null;
}

export default AlbaUserAuthor;
