// Typelizer digest c968369c7dbe899a86541184c89b1d67
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaOptionalKey = {
  /** Unique identifier */
  id: string;
  firstName: string;
  lastName?: string;
}

export default AlbaOptionalKey;
