// Typelizer digest 472a2113fcda840c96020c17180bddc5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaTupleType = {
  username: string;
  coordinates: [number, string];
}

export default AlbaTupleType;
