// Typelizer digest 71db3d9bf34a5c385ee61cc6b8b75abc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaComment} from '@/types'

type AlbaClassRef = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  reviewer?: AlbaUser | null;
  editor: AlbaUser;
  approver: AlbaUser | null;
  commentable: AlbaUser | AlbaComment;
  mixed_ref: AlbaUser | AlbaComment;
  contributors: Array<AlbaUser> | null;
}

export default AlbaClassRef;
