// Typelizer digest db979b1cb7cce82508675b644ff4a0d7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, UserRole} from '@/types'

type AlbaUser = {
  /** Unique identifier */
  id: string | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sir_name: string;
  role: UserRole;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latest_post: AlbaPost | null;
  /** Aliased posts collection */
  custom_key_posts?: Array<AlbaPost>;
  first_name: string;
}

export default AlbaUser;
