// Typelizer digest bef71d460b7d6744ecd4ffcfff704d4d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaInlineShape = {
  username: string;
  category: {
    id: number;
    label?: string;
  };
  revisions: Array<{
    version: number;
    tag?: string;
  }> | null;
  summary: {
    customer: {
      name: string;
      email?: string;
    };
    totals: {
      subtotal: number;
      grand_total: number;
    };
  };
  nickname?: string;
}

export default AlbaInlineShape;
