// Typelizer digest 4790e5a2230b13defe269b66a1e72081
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaMetaNil = {
  /** Unique identifier */
  id: string;
}

export default AlbaMetaNil;
