// Typelizer digest 88552ae4d26d939664649663de65bb4b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaCustomTypes = {
  /** Unique identifier */
  id: string;
  provider: 'cloudpayments' | 'tiptoppay';
  metadata: { name: string; visitorId: string | null };
  lookup: Record<string, number | null>;
  pair: [string | null, number];
  result: { ok: boolean } | { error: string };
  config: { retries: number | null } | null;
  status: 'active' | 'inactive' | null;
  kind: 'user' | null;
  tag: string | number;
}

export default AlbaCustomTypes;
