// Typelizer digest 7cafd490c69609b0bc35c9b87763a923
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedEmptyUser = AlbaUser
export default AlbaInheritedEmptyUser;
