// Typelizer digest 5d7018a2e0cea47a5750e3f933d511e2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser, AlbaPost, UserRole} from '@/types'

type AlbaUserSerializerFoo = {
  /** Unique identifier */
  id?: number | null;
  username: string;
  active: boolean;
  name: string;
  /** This is sir name from the name */
  sir_name: string;
  role: UserRole;
  invitor: AlbaUser | null;
  posts: Array<AlbaPost>;
  latest_post: AlbaPost | null;
  /** Aliased posts collection */
  custom_key_posts?: Array<AlbaPost>;
  first_name: string;
  created_at: string;
}

export default AlbaUserSerializerFoo;
