// Typelizer digest 550ec330711fc3e03e88df2b12636200
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaPoro = {
  foo: unknown;
  bar: string | null;
  details: {
    baz: unknown;
    qux: unknown;
  };
}

export default AlbaPoro;
