// Typelizer digest 7f672a83e202e247102a98031169bcb3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaInheritedCustomTypeUser = Omit<AlbaUser, 'id'> & {
  /** Unique identifier */
  id?: number | null;
}

export default AlbaInheritedCustomTypeUser;
