// Typelizer digest bf09f2e10cb2e24da87ab2b327019a64
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaPost, AlbaUser, AlbaComment} from '@/types'

type AlbaShowPage = {
  activity: AlbaUser;
  comments: Array<AlbaComment>;
  featured_posts: Array<AlbaPost>;
}

export default AlbaShowPage;
