// Typelizer digest 9c060c48e7ce2daf2de08fe1274c5d75
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AlbaTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

type AlbaTypeShortcutsWithMetadataTrait = {
  metadata_tags: Array<string>;
  counts?: Array<number>;
}

export default AlbaTypeShortcuts;
export type { AlbaTypeShortcutsWithMetadataTrait };
