// Typelizer digest becbc67b7686abf8082dd887bab566e1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsInheritedExtendedUser = AmsUser & {
  full_name: string;
}

export default AmsInheritedExtendedUser;
