// Typelizer digest 869626ee5b924928056c55c08b510d31
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsInheritedEmptyUser = AmsUser
export default AmsInheritedEmptyUser;
