// Typelizer digest 5433bc3b784834a0262db5290efa156f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AmsTypeShortcuts = {
  /** Unique identifier */
  id: string;
  nickname?: string;
  tags: Array<string>;
  roles?: Array<string>;
  status?: string | null;
  score?: number;
  bio?: string;
  level: Array<number>;
}

export default AmsTypeShortcuts;
