// Typelizer digest 52d217380ea2474bb65bbc6cb2d0356c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsPost} from '@/types'

type AmsUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts?: Array<AmsPost>;
}

export default AmsUserEmptyNested;
