// Typelizer digest 6207a51dbdd0a7fe7b23eb029ace9259
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser, AmsPost} from '@/types'

type AmsUserSerializerFoo = {
  /** Unique identifier */
  id?: number | null;
  username: string;
  active: boolean;
  name: string;
  first_name: string;
  created_at: string;
  invitor: AmsUser | null;
  posts: Array<AmsPost>;
}

export default AmsUserSerializerFoo;
