// Typelizer digest 1ca789c00972305c73b5c6d03e3fc832
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsPost} from '@/types'

type AmsUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts?: Array<AmsPost>;
}

export default AmsUserAuthor;
