// Typelizer digest 5bf48fda4dc99a6e53b6874229c357e7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersSorted = {
  /** Unique identifier */
  id: string;
  active: boolean;
  created_at: string;
  email: string;
  name: string;
  username: string;
}

export default OjSerializersSorted;
