// Typelizer digest 5ea94d0043781dde6ec03f53d155854f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser, OjSerializersPost} from '@/types'

type OjSerializersTransformKeys = {
  /** Unique identifier */
  id: string;
  username: string;
  active: boolean;
  name: string;
  invitor: OjSerializersUser | null;
  posts: Array<OjSerializersPost>;
  firstName: string;
  createdAt: string;
}

export default OjSerializersTransformKeys;
