// Typelizer digest fd05f272e8a97b80105258ef2b2e8f6e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersInheritedExtendedUser} from '@/types'

type OjSerializersInheritedDeepUser = OjSerializersInheritedExtendedUser & {
  updated_at: string;
}

export default OjSerializersInheritedDeepUser;
