// Typelizer digest 526b2d54114907f835a6b96c3f26f337
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersPost} from '@/types'

type OjSerializersUserAuthor = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  posts?: Array<OjSerializersPost>;
  avatar: unknown;
  typed_avatar: string | null;
}

export default OjSerializersUserAuthor;
