// Typelizer digest 64a761b01f86597712ff68783693aced
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersInheritedCustomTypeUser = Omit<OjSerializersUser, 'id'> & {
  /** Unique identifier */
  id?: number;
}

export default OjSerializersInheritedCustomTypeUser;
