// Typelizer digest 64fc804db4324d32cb92759ec1b3a84e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersArDelegate = {
  /** Unique identifier */
  id: string;
  name: string | null;
  user_username: string;
  author_active: boolean;
  user_role: number | null;
}

export default OjSerializersArDelegate;
