// Typelizer digest a69b959d850e19e02d66554f6ad3e7e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type OjSerializersVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { OjSerializersVerbatimModuleSyntax };
