// Typelizer digest 57db1d423bed0df2802a39487db12087
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersInheritedExtendedUser = OjSerializersUser & {
  full_name: string;
}

export default OjSerializersInheritedExtendedUser;
