// Typelizer digest 4d95ecf4562dc6fc529316f95ea01e4c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersArUser} from '@/types'

type OjSerializersArPost = {
  /** Unique identifier */
  id: string;
  title?: string | null;
  user: OjSerializersArUser | null;
}

export default OjSerializersArPost;
