// Typelizer digest 7b195beab6dd5c4927dfd363a05674a3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoPost} from '@/types'

type PankoUserEmptyNested = {
  /** Unique identifier */
  id: string;
  /** Author login handle */
  username: string | null;
  avatar: unknown;
  typed_avatar: string | null;
  posts: Array<PankoPost>;
}

export default PankoUserEmptyNested;
