// Typelizer digest 71f54db35cb35fb376e7689d6aaf1f34
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoArDelegate = {
  /** Unique identifier */
  id: string;
  name: string | null;
  user_username: string;
  author_active: boolean;
  user_role: number | null;
}

export default PankoArDelegate;
