// Typelizer digest 8d071004b825c6a22a75af90d42a9f08
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoVerbatimModuleSyntax = {
  /** Unique identifier */
  id: string;
  username: string;
}

export type { PankoVerbatimModuleSyntax };
