// Typelizer digest c97976cac9e4268bcb5c0bb5c85e0914
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser} from '@/types'

type PankoInheritedExtendedUser = PankoUser & {
  full_name: string;
}

export default PankoInheritedExtendedUser;
