// Typelizer digest 5712f58d36841ed080e8beafb8f0703c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoCustomTypes = {
  /** Unique identifier */
  id: string;
  provider: 'cloudpayments' | 'tiptoppay';
  metadata: { name: string; visitorId: string | null };
  lookup: Record<string, number | null>;
  pair: [string | null, number];
  result: { ok: boolean } | { error: string };
  config: { retries: number | null } | null;
  status: 'active' | 'inactive' | null;
  kind: 'user' | null;
  tag: string | number;
}

export default PankoCustomTypes;
