// Typelizer digest aa67d3877a096321b144a101acd5f89a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PankoComment = {
  /** Unique identifier */
  id: string;
  body: string;
  replies: Array<PankoComment>;
  parent?: PankoComment;
}

export default PankoComment;
