// Typelizer digest caa7a35856088c73c94628fcac418a73
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, FormDefinition, RouteOptions } from './runtime'
import { buildUrl, formAction } from './runtime'

export default {
  /** GET / */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/', {}, options),
    method: 'get',
  }),

  /** GET /pages/*path */
  show: (
    params: { path: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/pages/*path', params, options),
    method: 'get',
  }),
}
