// Typelizer digest ec9e7da356df24d52f0adb357655afa8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, FormDefinition, RouteOptions } from './runtime'
import { buildUrl, formAction } from './runtime'

export default {
  /** GET /users/:user_id/posts */
  userPosts: (
    params: { userId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/users/:user_id/posts', params, options),
    method: 'get',
  }),

  /** GET /users/:user_id/posts/:id */
  userPost: (
    params: { userId: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/users/:user_id/posts/:id', params, options),
    method: 'get',
  }),

  /** GET /posts */
  posts: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/posts', {}, options),
    method: 'get',
  }),

  /** POST /posts */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/posts', {}, options),
    method: 'post',
  }),

  /** GET /posts/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/posts/new', {}, options),
    method: 'get',
  }),

  /** GET /posts/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/posts/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /posts/:id */
  post: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/posts/:id', params, options),
    method: 'get',
  }),

  /** PATCH /posts/:id */
  update: Object.assign(
    (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): RouteDefinition<'patch'> => ({
      url: buildUrl('/posts/:id', params, options),
      method: 'patch',
    }),
    { form: (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): FormDefinition =>
      formAction(buildUrl('/posts/:id', params, options), 'patch') },
  ),

  /** DELETE /posts/:id */
  destroy: Object.assign(
    (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): RouteDefinition<'delete'> => ({
      url: buildUrl('/posts/:id', params, options),
      method: 'delete',
    }),
    { form: (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): FormDefinition =>
      formAction(buildUrl('/posts/:id', params, options), 'delete') },
  ),

  /** GET /archive(/:year)(/:month) */
  archive: (
    params: { year?: string | number; month?: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/archive(/:year)(/:month)', params, options),
    method: 'get',
  }),
}
