// Typelizer digest f1896934b6c25c8df12a6d54fdbb48d9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, FormDefinition, RouteOptions } from './runtime'
import { buildUrl, formAction } from './runtime'

export default {
  /** GET /users */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/users', {}, options),
    method: 'get',
  }),

  /** POST /users */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/users', {}, options),
    method: 'post',
  }),

  /** GET /users/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/users/new', {}, options),
    method: 'get',
  }),

  /** GET /users/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/users/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /users/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/users/:id', params, options),
    method: 'get',
  }),

  /** PATCH /users/:id */
  update: Object.assign(
    (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): RouteDefinition<'patch'> => ({
      url: buildUrl('/users/:id', params, options),
      method: 'patch',
    }),
    { form: (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): FormDefinition =>
      formAction(buildUrl('/users/:id', params, options), 'patch') },
  ),

  /** DELETE /users/:id */
  destroy: Object.assign(
    (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): RouteDefinition<'delete'> => ({
      url: buildUrl('/users/:id', params, options),
      method: 'delete',
    }),
    { form: (
      params: { id: string | number } | string | number,
      options?: RouteOptions,
    ): FormDefinition =>
      formAction(buildUrl('/users/:id', params, options), 'delete') },
  ),
}
